return {
    KNOWN_LANGUAGES = {
      { language = "abap", image = "text" },
      { language = "ansible", image = "ansible" },
      { language = "asciidoc", image = "asciidoc" },
      { language = "bat", image = "bat" },
      { language = "bazel", image = "bazel" },
      { language = "bibtex", image = "text" },
      { language = "citrinescript", image = "citrinescript" },
      { language = "clojure", image = "clojure" },
      { language = "cobol", image = "cobol" },
      { language = "coffeescript", image = "coffee" },
      { language = "c", image = "c" },
      { language = "cosmo", image = "cosmo" },
      { language = "cpp", image = "cpp" },
      { language = "csharp", image = "csharp" },
      { language = "css", image = "css" },
      { language = "cython", image = "cython" },
      { language = "diff", image = "manifest" },
      { language = "dockerfile", image = "docker" },
      { language = "fortran", image = "fortran" },
      { language = "fsharp", image = "fsharp" },
      { language = "git-commit", image = "manifest" },
      { language = "git-rebase", image = "manifest" },
      { language = "glsl", image = "glsl" },
      { language = "gml", image = "gml" },
      { language = "gleam", image = "gleam" },
      { language = "go", image = "go" },
      { language = "grain", image = "grain" },
      { language = "groovy", image = "groovy" },
      { language = "gamescript", image = "gamescript" },
      { language = "handlebars", image = "handlebars" },
      { language = "haml", image = "text" },
      { language = "holyc", image = "holyc" },
      { language = "html-eex", image = "heex" },
      { language = "html", image = "html" },
      { language = "hlsl", image = "hlsl" },
      { language = "ini", image = "manifest" },
      { language = "java", image = "java" },
      { language = "javascript", image = "js" },
      { language = "javascriptreact", image = "jsx" },
      { language = "jinja", image = "jinja" },
      { language = "jsx", image = "jsx" },
      { language = "json", image = "json" },
      { language = "jsonc", image = "json" },
      { language = "jule", image = "jule" },
      { language = "jupyter", image = "jupyter" },
      { language = "kivy", image = "kivy" },
      { language = "kag-script", image = "kag-script" },
      { language = "kirikiri-tpv-javascript", image = "kirikiri-tpv-javascript" },
      { language = "latex", image = "text" },
      { language = "less", image = "less" },
      { language = "lua", image = "lua" },
      { language = "luau", image = "luau" },
      { language = "makefile", image = "makefile" },
      { language = "markdown", image = "markdown" },
      { language = "MATLAB", image = "matlab" },
      { language = "moonscript", image = "moonscript" },
      { language = "mojo", image = "mojo" },
      { language = "objective-c", image = "objective-c" },
      { language = "objective-cpp", image = "objective-c" },
      { language = "odin", image = "odin" },
      { language = "onyx", image = "onyx" },
      { language = "opengoal", image = "opengoal" },
      { language = "opengoal-goos", image = "opengoal-goos" },
      { language = "opengoal-ir", image = "opengoal-ir" },
      { language = "perl", image = "perl" },
      { language = "perl6", image = "perl" },
      { language = "php", image = "php" },
      { language = "plaintext", image = "text" },
      { language = "powershell", image = "powershell" },
      { language = "jade", image = "pug" },
      { language = "pug", image = "pug" },
      { language = "prisma", image = "prisma" },
      { language = "python", image = "python" },
      { language = "qml", image = "qml" },
      { language = "r", image = "r" },
      { language = "racket", image = "racket" },
      { language = "razor", image = "cshtml" },
      { language = "reasonml", image = "reasonml" },
      { language = "rst", image = "restructuredtext" },
      { language = "ruby", image = "ruby" },
      { language = "rust", image = "rust" },
      { language = "scss", image = "scss" },
      { language = "sass", image = "scss" },
      { language = "shaderlab", image = "manifest" },
      { language = "shellscript", image = "shell" },
      { language = "slim", image = "text" },
      { language = "solidity", image = "solidity" },
      { language = "sql", image = "sql" },
      { language = "squirrel", image = "squirrel" },
      { language = "starlark", image = "bazel" },
      { language = "systemverilog", image = "systemverilog" },
      { language = "stylus", image = "stylus" },
      { language = "swift", image = "swift" },
      { language = "typescript", image = "ts" },
      { language = "typescriptreact", image = "tsx" },
      { language = "templ", image = "templ" },
      { language = "tex", image = "tex" },
      { language = "umjunsik", image = "umm" },
      { language = "vb", image = "vb" },
      { language = "verse", image = "verse" },
      { language = "vue", image = "vue" },
      { language = "vue-html", image = "vue" },
      { language = "zura", image = "zura" },
      { language = "xml", image = "xml" },
      { language = "xsl", image = "xml" },
      { language = "yaml", image = "yaml" },
      { language = "zenscript", image = "zs" }
    },
    
    KNOWN_EXTENSIONS = {
      ["nodemon.json"] = { image = "nodemon" },
      ["package.json"] = { image = "npm" },
      ["turbo.json"] = { image = "turbo" },
      
      ["vercel.json"] = { image = "vercel" },
      ["now.json"] = { image = "vercel" },
      [".prettierrc"] = { image = "prettier" },
      [".prettierrc.toml"] = { image = "prettier" },
      [".prettierrc.yml"] = { image = "prettier" },
      [".prettierrc.yaml"] = { image = "prettier" },
      [".prettierrc.json"] = { image = "prettier" },
      [".prettierrc.js"] = { image = "prettier" },
      [".eslintignore"] = { image = "eslint" },
      [".eslintrc"] = { image = "eslint" },
      [".eslintrc.json"] = { image = "eslint" },
      [".eslintrc.js"] = { image = "eslint" },
      [".nowignore"] = { image = "vercel" },
      [".vercelignore"] = { image = "vercel" },

      ["prettier.config.js"] = { image = "prettier" },

      ["vue.config.js"] = { image = "vueconfig" },
      ["vue.config.ts"] = { image = "vueconfig" },

      ["vite.config.js"] = { image = "viteconfig" },
      ["vite.config.ts"] = { image = "viteconfig" },

      ["vitest.config.js"] = { image = "vitestconfig" },
      ["vitest.config.ts"] = { image = "vitestconfig" },

      ["jest.config.js"] = { image = "jest" },
      ["jest.config.ts"] = { image = "jest" },

      ["tailwind.config.js"] = { image = "tailwind" },
      ["tailwind.config.ts"] = { image = "tailwind" },

      ["gatsby-browser.js"] = { image = "gatsbyjs" },
      ["gatsby-config.js"] = { image = "gatsbyjs" },
      ["gatsby-node.js"] = { image = "gatsbyjs" },
      ["gatsby-ssr.js"] = { image = "gatsbyjs" },

      ["webpack.config.js"] = { image = "webpack" },
      ["webpack.config.ts"] = { image = "webpack" },
      ["webpack.config.cjs"] = { image = "webpack" },
      ["webpack.config.mjs"] = { image = "webpack" },

      ["babel.config.mjs"] = { image = "babel" },
      ["babel.config.js"] = { image = "babel" },
      ["babel.config.cjs"] = { image = "babel" },
      ["babel.config.mjs"] = { image = "babel" },
      
      [".ahk"] = { image = "ahk" },
      [".ahkl"] = { image = "ahk" },
      [".adoc"] = { image = "asciidoc" },
      [".asciidoc"] = { image = "asciidoc" },
      [".astro"] = { image = "astro" },
      [".astro.config.mjs"] = { image = "astroconfig" },
      ["androidmanifest.xml"] = { image = "android" },
      [".bp"] = { image = "android" },
      [".applescript"] = { image = "applescript" },
      [".ino"] = { image = "arduino" },
      [".swf"] = { image = "as" },
      [".as"] = { image = "as" },
      [".jsfl"] = { image = "as" },
      [".swc"] = { image = "as" },
      [".asp"] = { image = "asp" },
      [".asax"] = { image = "asp" },
      [".ascx"] = { image = "asp" },
      [".ashx"] = { image = "asp" },
      [".asmx"] = { image = "asp" },
      [".aspx"] = { image = "asp" },
      [".axd"] = { image = "asp" },
      [".au3"] = { image = "autoit" },
      [".bat"] = { image = "bat" },
      [".batch"] = { image = "bat" },
      [".cmd"] = { image = "bat" },
      [".reg"] = { image = "bat" },
      [".casc"] = { image = "casc" },
      [".cas"] = { image = "casc" },
      [".ces"] = { image = "citrinescript" },
      [".cfc"] = { image = "coldfusion" },
      [".cfm"] = { image = "coldfusion" },
      ["circle.yml"] = { image = "circleci" },
      [".clj"] = { image = "clojure" },
      [".cl2"] = { image = "clojure" },
      [".cljc"] = { image = "clojure" },
      [".cljx"] = { image = "clojure" },
      [".hic"] = { image = "clojure" },
      [".cmake"] = { image = "cmake" },
      ["CMakeLists.txt"] = { image = "cmake" },
      [".cbl"] = { image = "cobol" },
      [".cob"] = { image = "cobol" },
      [".coffee"] = { image = "coffee" },
      [".cjsx"] = { image = "coffee" },
      [".coffee.ecr"] = { image = "coffee" },
      [".coffee.erb"] = { image = "coffee" },
      [".litcoffee"] = { image = "coffee" },
      [".iced"] = { image = "coffee" },
      [".cos"] = { image = "cosmo" },
      [".⭐"] = { image = "cosmo" },
      [".c"] = { image = "c" },
      [".cats"] = { image = "cpp" },
      [".idc"] = { image = "cpp" },
      [".w"] = { image = "cpp" },
      [".nc"] = { image = "cpp" },
      [".upc"] = { image = "cpp" },
      [".xpm"] = { image = "cpp" },
      [".cs"] = { image = "csharp" },
      [".csx"] = { image = "csharp" },
      [".cshtml"] = { image = "razor" },
      [".csproj"] = { image = "csproj" },
      [".css"] = { image = "css" },
      [".css.map"] = { image = "cssmap" },
      [".cu"] = { image = "cuda" },
      [".pyx"] = { image = "cython" },
      [".dart"] = { image = "dart" },
      [".dfm"] = { image = "delphi" },
      [".dpr"] = { image = "delphi" },
      [".dsc"] = { image = "denizen" },
      [".dm"] = { image = "dm" },
      [".dme"] = { image = "dm" },
      [".dmm"] = { image = "dm" },
      [".editorconfig"] = { image = "editorconfig" },
      [".ejs"] = { image = "ejs" },
      [".ex"] = { image = "elixir" },
      [".elm"] = { image = "elm" },
      [".env"] = { image = "env" },
      [".erl"] = { image = "erlang" },
      [".beam"] = { image = "erlang" },
      [".hrl"] = { image = "erlang" },
      [".xrl"] = { image = "erlang" },
      [".yrl"] = { image = "erlang" },
      [".app.src"] = { image = "erlang" },
      [".flowconfig"] = { image = "flowconfig" },
      [".fs"] = { image = "fsharp" },
      [".fsi"] = { image = "fsharp" },
      [".fsscript"] = { image = "fsharp" },
      [".fsx"] = { image = "fsharp" },
      [".gml"] = { image = "gml" },
      [".gleam"] = { image = "gleam" },
      [".go"] = { image = "go" },
      [".gd"] = { image = "godot" },
      [".gr"] = { image = "grain" },
      [".gradle"] = { image = "gradle" },
      ["gradlew"] = { image = "gradle" },
      [".gql"] = { image = "graphql" },
      [".graphql"] = { image = "graphql" },
      [".groovy"] = { image = "groovy" },
      [".gsh"] = { image = "groovy" },
      [".prg"] = { image = "harbour" },
      [".ha"] = { image = "hare" },
      [".hbp"] = { image = "harbour" },
      [".hbc"] = { image = "harbour" },
      [".rc"] = { image = "harbour" },
      [".fmg"] = { image = "harbour" },
      [".hs"] = { image = "haskell" },
      [".hsc"] = { image = "haskell" },
      [".c2hs"] = { image = "haskell" },
      [".c3"] = { image = "c3" },
      [".lhs"] = { image = "haskell" },
      [".heex"] = { image = "heex" },
      ["heroku.yml"] = { image = "heroku" },
      [".hjson"] = { image = "hjson" },
      [".hc"] = { image = "holyc" },
      [".http"] = { image = "http" },
      [".rest"] = { image = "http" },
      [".jar"] = { image = "jar" },
      [".java"] = { image = "java" },
      [".j2"] = { image = "jinja" },
      [".jinja"] = { image = "jinja" },
      [".js"] = { image = "js" },
      [".es6"] = { image = "js" },
      [".es"] = { image = "js" },
      [".mjs"] = { image = "js" },
      [".js.map"] = { image = "jsmap" },
      [".json"] = { image = "json" },
      [".jsonc"] = { image = "json" },
      [".jsx"] = { image = "jsx" },
      [".jule"] = { image = "jule" },
      [".ipynb"] = { image = "jupyter" },
      [".kv"] = { image = "kivy" },
      [".ks"] = { image = "kag-script" },
      [".tjs"] = { image = "kirikiri-tpv-javascript" },
      [".less"] = { image = "less" },
      [".log"] = { image = "log" },
      [".ls"] = { image = "livescript" },
      [".sln"] = { image = "csproj" },
      [".moon"] = { image = "moonscript" },
      [".nim"] = { image = "nim" },
      [".nims"] = { image = "nim" },
      [".nimble"] = { image = "nim" },
      [".nix"] = { image = "nix" },
      [".npmrc"] = { image = "npm" },
      [".npmignore"] = { image = "npm" },
      [".nut"] = { image = "squirrel" },
      [".pch"] = { image = "objective-c" },
      [".x"] = { image = "objective-c" },
      [".mt"] = { image = "metal" },
      [".odin"] = { image = "odin" },
      [".onyx"] = { image = "onyx" },
      [".lpr"] = { image = "pascal" },
      [".inc"] = { image = "pawn" },
      [".sma"] = { image = "pawn" },
      [".sp"] = { image = "sourcepawn" },
      [".al"] = { image = "perl" },
      [".pl6"] = { image = "perl" },
      [".6pm"] = { image = "perl" },
      [".nqp"] = { image = "perl" },
      [".p6l"] = { image = "perl" },
      [".pod6"] = { image = "perl" },
      [".pony"] = { image = "ponylang" },
      [".pcss"] = { image = "postcss" },
      [".ps1xml"] = { image = "powershell" },
      [".prettierignore"] = { image = "prettier" },
      ["prisma.yml"] = { image = "prisma" },
      [".pde"] = { image = "processing" },
      [".jade"] = { image = "pug" },
      [".pug"] = { image = "pug" },
      [".purs"] = { image = "purescript" },
      [".ipy"] = { image = "python" },
      [".isolate"] = { image = "python" },
      [".pep"] = { image = "python" },
      [".pyde"] = { image = "python" },
      [".tac"] = { image = "python" },
      [".wsgi"] = { image = "python" },
      [".xpy"] = { image = "python" },
      [".rpy"] = { image = "python" },
      [".razor"] = { image = "razor" },
      [".rst"] = { image = "restructuredtext" },
      [".watchr"] = { image = "ruby" },
      [".rs"] = { image = "rust" },
      [".sh-session"] = { image = "shell" },
      [".inputrc"] = { image = "shell" },
      [".tmux"] = { image = "shell" },
      [".profile"] = { image = "shell" },
      [".tcsh"] = { image = "shell" },
      [".csh"] = { image = "shell" },
      [".sk"] = { image = "skript" },
      [".sqf"] = { image = "sqf" },
      [".ddl"] = { image = "sql" },
      [".udf"] = { image = "sql" },
      [".hql"] = { image = "sql" },
      [".rkt"] = { image = "racket" },
      [".viw"] = { image = "sql" },
      [".prc"] = { image = "sql" },
      [".cql"] = { image = "sql" },
      [".db2"] = { image = "sql" },
      [".svelte"] = { image = "svelte" },
      [".svg"] = { image = "svg" },
      [".swift"] = { image = "swift" },
      [".ltx"] = { image = "tex" },
      [".aux"] = { image = "tex" },
      [".sty"] = { image = "tex" },
      [".dtx"] = { image = "tex" },
      [".cls"] = { image = "tex" },
      [".ins"] = { image = "tex" },
      [".lbx"] = { image = "tex" },
      [".mkiv"] = { image = "tex" },
      [".rtf"] = { image = "text" },
      [".msg"] = { image = "text" },
      [".templ"] = { image = "templ" },
      [".toml"] = { image = "toml" },
      [".travis.yml"] = { image = "travis" },
      [".ts.map"] = { image = "tsmap" },
      [".ts"] = { image = "ts" },
      [".tsx"] = { image = "tsx" },
      [".twig"] = { image = "twig" },
      [".umm"] = { image = "umm" },
      [".v"] = { image = "v" },
      [".vh"] = { image = "v" },
      [".vala"] = { image = "vala" },
      [".vapi"] = { image = "vala" },
      [".vb"] = { image = "vb" },
      [".vbs"] = { image = "vb" },
      [".vbhtml"] = { image = "vb" },
      [".vbproj"] = { image = "vb" },
      [".vba"] = { image = "vba" },
      [".vcxproj"] = { image = "vcxproj" },
      [".verse"] = { image = "verse" },
      [".vscodeignore"] = { image = "vscodeignore" },
      [".vue"] = { image = "vue" },
      [".zu"] = { image = "zura" },
      [".zura"] = { image = "zura" },
      [".wat"] = { image = "wasm" },
      [".wast"] = { image = "wasm" },
      [".wasm"] = { image = "wasm" },
      [".xml"] = { image = "xml" },
      [".xaml"] = { image = "xaml" },
      [".yarnrc"] = { image = "yarn" },
      [".zig"] = { image = "zig" },
      [".maeel"] = { image = "maeel" },
      [".🔥"] = { image = "mojo" },
      [".zs"] = { image = "zs" },
      ["webpack.config.js"] = { image = "webpack" },
      ["webpack.config.ts"] = { image = "webpack" },
      ["Makefile"] = { image = "makefile" },
      
      [".prettierrc"] = { image = "prettier" },
      [".prettierrc.json"] = { image = "prettier" },
      [".prettierrc.js"] = { image = "prettier" },
      [".prettierrc.yml"] = { image = "prettier" },
      [".prettierrc.yaml"] = { image = "prettier" },
      [".prettierrc.toml"] = { image = "prettier" },
      [".prettierignore"] = { image = "prettier" },
      ["prettier.config.js"] = { image = "prettier" },
      ["prettier.config.ts"] = { image = "prettier" },
      
      [".eslintrc"] = { image = "eslint" },
      [".eslintrc.json"] = { image = "eslint" },
      [".eslintrc.js"] = { image = "eslint" },
      [".eslintignore"] = { image = "eslint" },
      ["eslint.config.js"] = { image = "eslint" },
      ["eslint.config.ts"] = { image = "eslint" },

      ["go.mod"] = { image = "go" },
      ["go.sum"] = { image = "go" },

      [".lua"] = { image = "lua" },
      [".luau"] = { image = "luau" },
      [".sol"] = { image = "solidity" },
      [".md"] = { image = "markdown" },
      [".mdx"] = { image = "markdownx" },
      [".marko"] = { image = "marko" },
      [".m"] = { image = "matlab" },
      [".yaml"] = { image = "yaml" },
      [".yml"] = { image = "yaml" },
      [".tf"] = { image = "terraform" },
      [".tfvars"] = { image = "terraform" },
      [".mojo"] = { image = "mojo" },
      [".html"] = { image = "html" },
      [".htm"] = { image = "html" },
      [".py"] = { image = "python" },
      [".rb"] = { image = "ruby" },
      [".php"] = { image = "php" },
      [".cpp"] = { image = "cpp" },
      [".cc"] = { image = "cpp" },
      [".cxx"] = { image = "cpp" },
      [".h"] = { image = "cpp" },
      [".hpp"] = { image = "cpp" },
      [".hxx"] = { image = "cpp" },
      [".scala"] = { image = "scala" },
      [".sc"] = { image = "scala" },
      [".sass"] = { image = "scss" },
      [".scss"] = { image = "scss" },
      [".sh"] = { image = "shell" },
      [".bash"] = { image = "shell" },
      [".zsh"] = { image = "shell" },
      [".fish"] = { image = "shell" },
      [".sql"] = { image = "sql" },
      [".styl"] = { image = "stylus" },
      [".stylus"] = { image = "stylus" },
      [".sv"] = { image = "systemverilog" },
      [".svh"] = { image = "systemverilog" },
      [".tex"] = { image = "tex" },
      [".txt"] = { image = "text" },
      [".text"] = { image = "text" },
      [".r"] = { image = "r" },
      [".R"] = { image = "r" },
      [".Rprofile"] = { image = "r" },
      [".rsx"] = { image = "r" },
      [".rd"] = { image = "r" },
      [".res"] = { image = "reasonml" },
      [".rei"] = { image = "reasonml" },
      [".resi"] = { image = "reasonml" },
      [".perl"] = { image = "perl" },
      [".pl"] = { image = "perl" },
      [".pm"] = { image = "perl" },
      [".t"] = { image = "perl" },
      [".pod"] = { image = "perl" },
      [".pas"] = { image = "pascal" },
      [".pascal"] = { image = "pascal" },
      [".pp"] = { image = "pascal" },
      [".mm"] = { image = "objective-c" },
      [".m"] = { image = "objective-c" },
      [".ml"] = { image = "ocaml" },
      [".mli"] = { image = "ocaml" },
      [".mll"] = { image = "ocaml" },
      [".mly"] = { image = "ocaml" },
      [".eliom"] = { image = "ocaml" },
      [".eliomi"] = { image = "ocaml" },
      [".bf"] = { image = "brainfuck" },
      [".b"] = { image = "brainfuck" },
      [".d"] = { image = "d" },
      [".di"] = { image = "d" },
      [".cr"] = { image = "crystal" },
      [".ecr"] = { image = "crystal" },
      [".jl"] = { image = "julia" },
      [".jil"] = { image = "julia" },
      [".kt"] = { image = "kotlin" },
      [".kts"] = { image = "kotlin" },
      [".ktm"] = { image = "kotlin" },
      [".lisp"] = { image = "lisp" },
      [".lsp"] = { image = "lisp" },
      [".l"] = { image = "lisp" },
      [".ny"] = { image = "lisp" },
      [".nl"] = { image = "lisp" },
      [".podsl"] = { image = "lisp" },
      [".sexp"] = { image = "lisp" },
      [".ss"] = { image = "lisp" },
      [".scm"] = { image = "lisp" },
      [".f"] = { image = "fortran" },
      [".for"] = { image = "fortran" },
      [".f90"] = { image = "fortran" },
      [".f95"] = { image = "fortran" },
      [".f03"] = { image = "fortran" },
      [".f08"] = { image = "fortran" },
      [".f18"] = { image = "fortran" },
      [".exe"] = { image = "bat" },
      [".com"] = { image = "bat" },
      [".msi"] = { image = "bat" },
      [".so"] = { image = "assembly" },
      [".o"] = { image = "assembly" },
      [".a"] = { image = "assembly" },
      [".out"] = { image = "assembly" },
      [".s"] = { image = "assembly" },
      [".asm"] = { image = "assembly" },
      [".agc"] = { image = "assembly" },
      [".ko"] = { image = "assembly" },
      [".lst"] = { image = "assembly" },
      [".swp"] = { image = "assembly" },
      [".DS_Store"] = { image = "assembly" },
      [".cson"] = { image = "manifest" },
      [".json5"] = { image = "manifest" },
      [".ndjson"] = { image = "manifest" },
      [".fea"] = { image = "manifest" },
      [".json.eex"] = { image = "manifest" },
      [".pawn"] = { image = "pawn" },
      [".proto"] = { image = "manifest" },
      [".pytb"] = { image = "manifest" },
      [".pydeps"] = { image = "manifest" },
      [".pot"] = { image = "manifest" },
      [".po"] = { image = "manifest" },
      [".ejson"] = { image = "manifest" },
      [".edn"] = { image = "manifest" },
      [".eam.fs"] = { image = "manifest" },
      [".qml"] = { image = "manifest" },
      [".qbs"] = { image = "manifest" },
      [".ston"] = { image = "manifest" },
      [".ttl"] = { image = "manifest" },
      [".rviz"] = { image = "manifest" },
      [".syntax"] = { image = "manifest" },
      [".webmanifest"] = { image = "manifest" },
      [".info"] = { image = "text" },
      [".utf8"] = { image = "text" },
      [".utxt"] = { image = "text" },
      [".mdown"] = { image = "markdown" },
      [".markdown"] = { image = "markdown" },
      [".mkd"] = { image = "markdown" },
      [".mkdown"] = { image = "markdown" },
      [".mdwn"] = { image = "markdown" },
      [".mkdn"] = { image = "markdown" },
      [".rmd"] = { image = "markdown" },
      [".ron"] = { image = "markdown" },
      [".pmd"] = { image = "markdown" },
      [".pw"] = { image = "pawn" },
      [".pwn"] = { image = "pawn" },
      [".p"] = { image = "pawn" },
      [".php3"] = { image = "php" },
      [".php4"] = { image = "php" },
      [".php5"] = { image = "php" },
      [".phps"] = { image = "php" },
      [".phpt"] = { image = "php" },
      [".phtml"] = { image = "php" },
      [".php_cs"] = { image = "php" },
      [".ps1"] = { image = "powershell" },
      [".psd1"] = { image = "powershell" },
      [".psm1"] = { image = "powershell" },
      [".pyw"] = { image = "python" },
      [".py3"] = { image = "python" },
      [".pyt"] = { image = "python" },
      [".pyi"] = { image = "python" },
      [".pyc"] = { image = "assembly" },
      [".pyo"] = { image = "assembly" },
      [".rpyc"] = { image = "assembly" },
      [".rpyb"] = { image = "assembly" },
      [".gvy"] = { image = "groovy" },
      [".gy"] = { image = "groovy" },
      [".gsc"] = { image = "gamescript" },
      [".csc"] = { image = "gamescript" },
      [".hbs"] = { image = "handlebars" },
      [".handlebars"] = { image = "handlebars" },
      [".mustache"] = { image = "handlebars" },
      [".hx"] = { image = "haxe" },
      [".hxml"] = { image = "haxe" },
      [".html"] = { image = "html" },
      [".xhtml"] = { image = "html" },
      [".shtml"] = { image = "html" },
      [".htm"] = { image = "html" },
      [".hlsl"] = { image = "hlsl" },
      [".cginc"] = { image = "hlsl" },
      [".cg"] = { image = "hlsl" },
      [".shader"] = { image = "hlsl" },
      [".fx"] = { image = "hlsl" },
      [".glsl"] = { image = "glsl" },
      [".vert"] = { image = "glsl" },
      [".frag"] = { image = "glsl" },
      [".geom"] = { image = "glsl" },
      [".tesc"] = { image = "glsl" },
      [".tese"] = { image = "glsl" },
      [".comp"] = { image = "glsl" },
      [".rgen"] = { image = "glsl" },
      [".rint"] = { image = "glsl" },
      [".rahit"] = { image = "glsl" },
      [".rchit"] = { image = "glsl" },
      [".rmiss"] = { image = "glsl" },
      [".rcall"] = { image = "glsl" },
      [".mesh"] = { image = "glsl" },
      [".task"] = { image = "glsl" },
      [".vsh"] = { image = "glsl" },
      [".fsh"] = { image = "glsl" },
      [".gsh"] = { image = "glsl" },
      [".exs"] = { image = "elixir" },
      [".eex"] = { image = "elixir" },
      [".leex"] = { image = "elixir" },
      [".cljs"] = { image = "clojure" },
      [".cljscm"] = { image = "clojure" },
      [".gyp"] = { image = "python" },
      [".gypi"] = { image = "python" },
      [".ru"] = { image = "ruby" },
      [".ruby"] = { image = "ruby" },
      [".erb"] = { image = "ruby" },
      [".gemspec"] = { image = "ruby" },
      [".god"] = { image = "ruby" },
      [".mspec"] = { image = "ruby" },
      [".pluginspec"] = { image = "ruby" },
      [".podspec"] = { image = "ruby" },
      [".rabl"] = { image = "ruby" },
      [".rake"] = { image = "ruby" },
      [".opal"] = { image = "ruby" },
      [".jbuilder"] = { image = "ruby" },
      [".rbuild"] = { image = "ruby" },
      [".rbw"] = { image = "ruby" },
      [".rbx"] = { image = "ruby" },
      [".builder"] = { image = "ruby" },
      [".rbxl"] = { image = "luau" },
      [".rbxlx"] = { image = "luau" },
      [".rbxm"] = { image = "luau" },
      [".rbxs"] = { image = "luau" },
      [".mysql"] = { image = "sql" },
      [".mysqldata"] = { image = "sql" },
      [".ipp"] = { image = "cpp" },
      [".tpp"] = { image = "cpp" },
      [".tcc"] = { image = "cpp" },
      [".inl"] = { image = "cpp" },
      [".la"] = { image = "assembly" },
      [".lo"] = { image = "assembly" },
      [".a51"] = { image = "assembly" },
      [".axf"] = { image = "assembly" },
      [".elf"] = { image = "assembly" },
      [".prx"] = { image = "assembly" },
      [".puff"] = { image = "assembly" },
      [".z80"] = { image = "assembly" },
      [".objdump"] = { image = "assembly" },
      [".bsdiff"] = { image = "assembly" },
      [".bin"] = { image = "assembly" },
      [".dat"] = { image = "assembly" },
      [".pak"] = { image = "assembly" },
      [".pdb"] = { image = "assembly" },
      [".d-objdump"] = { image = "assembly" },
      [".gcode"] = { image = "assembly" },
      [".gco"] = { image = "assembly" },
      [".geo"] = { image = "manifest" },
      [".topo"] = { image = "manifest" },
      [".tex"] = { image = "tex" },
      [".texi"] = { image = "tex" },
      [".mki"] = { image = "tex" },
      [".mkii"] = { image = "tex" },
      [".mkiv"] = { image = "tex" },
      [".mkvi"] = { image = "tex" },
      [".mk"] = { image = "makefile" },
      [".mak"] = { image = "makefile" },
      [".make"] = { image = "makefile" },
      
      -- Special filenames without extensions
      ["Gemfile"] = { image = "gemfile" },
      ["Gemfile.lock"] = { image = "gemfile" },
      ["Procfile"] = { image = "heroku" },
      ["procfile"] = { image = "heroku" },
      ["PROCFILE"] = { image = "heroku" },
      ["Gruntfile.js"] = { image = "gruntfile" },
      ["Gruntfile.coffee"] = { image = "gruntfile" },
      ["gruntfile.js"] = { image = "gruntfile" },
      ["gruntfile.coffee"] = { image = "gruntfile" },
      ["Emakefile"] = { image = "erlang" },
      ["rebar.config"] = { image = "erlang" },
      ["rebar.lock"] = { image = "erlang" },
      ["rebar.config.lock"] = { image = "erlang" },
      ["Rexfile"] = { image = "perl" },
      ["Phakefile"] = { image = "php" },
      ["pkginfo"] = { image = "manifest" },
      ["METADATA.pb"] = { image = "manifest" },
      ["mime.types"] = { image = "manifest" },
      ["Cargo.toml"] = { image = "cargo" },
      ["Cargo.lock"] = { image = "cargo" },
      ["cargo.toml"] = { image = "cargo" },
      ["cargo.lock"] = { image = "cargo" },
      ["BUILD"] = { image = "bazel" },
      ["WORKSPACE"] = { image = "bazel" },
      [".bzl"] = { image = "bazel" },
      [".bazel"] = { image = "bazel" },
      [".bazelrc"] = { image = "bazel" },
      [".star"] = { image = "bazel" },
      [".sky"] = { image = "bazel" },
      [".bowerrc"] = { image = "bower" },
      ["bower.json"] = { image = "bower" },
      ["Bowerfile"] = { image = "bower" },
      [".appveyor.yml"] = { image = "appveyor" },
      ["appveyor.yml"] = { image = "appveyor" },
      [".codeclimate.yml"] = { image = "codeclimate" },
      [".codeclimate.json"] = { image = "codeclimate" },
      ["contenthook.config.ts"] = { image = "contenthook" },
      ["contenthook.config.cjs"] = { image = "contenthook" },
      ["contenthook.config.mjs"] = { image = "contenthook" },
      ["contenthook.config.js"] = { image = "contenthook" },
      [".firebaserc"] = { image = "firebase" },
      ["firebase.json"] = { image = "firebase" },
      [".git"] = { image = "git" },
      [".keep"] = { image = "git" },
      [".mailmap"] = { image = "git" },
      [".gitignore"] = { image = "git" },
      [".gitattributes"] = { image = "git" },
      [".gitmodules"] = { image = "git" },
      ["gulpfile.js"] = { image = "gulp" },
      [".babelrc"] = { image = "babel" },
      [".irbrc"] = { image = "ruby" },
      [".gemrc"] = { image = "ruby" },
      [".pryrc"] = { image = "ruby" },
      [".ruby-gemset"] = { image = "ruby" },
      [".ruby-version"] = { image = "ruby" },
      ["Appraisals"] = { image = "ruby" },
      ["Rakefile"] = { image = "ruby" },
      ["Rakefile.lock"] = { image = "ruby" },
      ["Buildfile"] = { image = "ruby" },
      ["buildfile"] = { image = "ruby" },
      ["Capfile"] = { image = "ruby" },
      ["Dangerfile"] = { image = "ruby" },
      ["Deliverfile"] = { image = "ruby" },
      ["Fastfile"] = { image = "ruby" },
      ["Guardfile"] = { image = "ruby" },
      ["Jarfile"] = { image = "ruby" },
      ["Mavenfile"] = { image = "ruby" },
      ["Podfile"] = { image = "ruby" },
      ["Puppetfile"] = { image = "ruby" },
      ["Snapfile"] = { image = "ruby" },
      ["rails"] = { image = "ruby" },
      ["SConstruct"] = { image = "python" },
      ["SConscript"] = { image = "python" },
      ["Snakefile"] = { image = "python" },
      ["WATCHLISTS"] = { image = "python" },
      ["wscript"] = { image = "python" },
      [".pypirc"] = { image = "python" },
      [".pythonrc"] = { image = "python" },
      [".python-venv"] = { image = "python" },
      ["pypirc"] = { image = "python" },
      ["pythonrc"] = { image = "python" },
      ["python-venv"] = { image = "python" },
      ["configure"] = { image = "shell" },
      ["config.guess"] = { image = "shell" },
      ["config.rpath"] = { image = "shell" },
      ["config.status"] = { image = "shell" },
      ["config.sub"] = { image = "shell" },
      ["depcomp"] = { image = "shell" },
      ["libtool"] = { image = "shell" },
      ["compile"] = { image = "shell" },
      [".login"] = { image = "shell" },
      [".profile"] = { image = "shell" },
      ["login"] = { image = "shell" },
      ["profile"] = { image = "shell" },
      [".cshrc"] = { image = "shell" },
      ["cshrc"] = { image = "shell" },
      [".bash_profile"] = { image = "shell" },
      [".bash_login"] = { image = "shell" },
      [".bash_logout"] = { image = "shell" },
      [".bash_history"] = { image = "shell" },
      [".bash_prompt"] = { image = "shell" },
      ["bash_profile"] = { image = "shell" },
      ["bash_login"] = { image = "shell" },
      ["bash_logout"] = { image = "shell" },
      ["bash_history"] = { image = "shell" },
      ["bash_prompt"] = { image = "shell" },
      [".bashrc"] = { image = "shell" },
      ["bashrc"] = { image = "shell" },
      ["_osc"] = { image = "shell" },
      ["config"] = { image = "shell" },
      ["install-sh"] = { image = "shell" },
      ["PKGBUILD"] = { image = "shell" },
      [".ksh"] = { image = "shell" },
      [".mksh"] = { image = "shell" },
      [".pdksh"] = { image = "shell" },
      [".zsh"] = { image = "shell" },
      [".zsh-theme"] = { image = "shell" },
      [".zsh_history"] = { image = "shell" },
      [".antigen"] = { image = "shell" },
      [".zpreztorc"] = { image = "shell" },
      [".zlogin"] = { image = "shell" },
      [".zlogout"] = { image = "shell" },
      [".zprofile"] = { image = "shell" },
      [".zshenv"] = { image = "shell" },
      [".zshrc"] = { image = "shell" },
      ["antigen"] = { image = "shell" },
      ["zpreztorc"] = { image = "shell" },
      ["zlogin"] = { image = "shell" },
      ["zlogout"] = { image = "shell" },
      ["zprofile"] = { image = "shell" },
      ["zshenv"] = { image = "shell" },
      ["zshrc"] = { image = "shell" },
      [".fish"] = { image = "shell" },
      [".fishrc"] = { image = "shell" },
      ["fishrc"] = { image = "shell" },
      ["BSDmakefile"] = { image = "makefile" },
      ["GNUmakefile"] = { image = "makefile" },
      ["makefile.sco"] = { image = "makefile" },
      ["Kbuild"] = { image = "makefile" },
      ["makefile"] = { image = "makefile" },
      ["mkfile"] = { image = "makefile" },
      [".qmake"] = { image = "makefile" },
      ["qmake"] = { image = "makefile" },
      ["mk.config"] = { image = "makefile" },
      ["Dockerfile"] = { image = "docker" },
      ["dockerfile"] = { image = "docker" },
      [".dockerfile"] = { image = "docker" },
      [".dockerignore"] = { image = "docker" },
      ["docker-compose.yml"] = { image = "docker" },
      ["docker-compose.yaml"] = { image = "docker" },
      ["docker-sync.yml"] = { image = "docker" },
      ["mix.exs"] = { image = "elixir" },
      ["mix.ex"] = { image = "elixir" },
      ["mix.lock"] = { image = "elixir" },
      ["angular.js"] = { image = "angular" },
      ["Angular.js"] = { image = "angular" },
      [".ng"] = { image = "angular" },
      ["yarn.lock"] = { image = "yarn" },
      ["yarn"] = { image = "yarn" },
      [".d.ts"] = { image = "typescript-def" }
    }
  }