name: Issue report
description: Report any errors, bugs, or unexpected behaviors related to presence.nvim
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Before reporting, please search [existing issues](https://github.com/andweeb/presence.nvim/issues) and make sure that presence.nvim is updated to the latest version.
  - type: textarea
    attributes:
      label: "Description"
      description: "A short summary of the error, bug, or unexpected behavior you're facing."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Neovim version"
      description: "Output of `nvim --version`"
      render: markdown
      placeholder: |
        NVIM v0.6.0-dev+209-g0603eba6e
        Build type: Release
        LuaJIT 2.1.0-beta3
    validations:
      required: true
  - type: input
    attributes:
      label: "OS information"
      placeholder: "macOS 12.0.1"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce the issue with your config(s) if applicable"
      placeholder: |
        1. Setup presence.nvim with `require("presence"):setup({...})`
        2. Run Neovim with `nvim test.txt`
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Logs"
      description: "The full list of `:messages` from one or more `nvim` instances"
    validations:
      required: true
